---
substitutions:
  # id_prefix: ratratgdov25
  # friendly_name: "ratratgdov2.5"
  uart_tx_pin: GPIO1
  uart_rx_pin: GPIO3
  input_obst_pin: GPIO13
  status_door_pin: GPIO16
  status_obstruction_pin: GPIO15
  dry_contact_open_pin: GPIO14
  dry_contact_close_pin: GPIO12
  dry_contact_light_pin: GPIO0

web_server:

esphome:
  name: ${id_prefix}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: rat-ratgdo.esphome
    version: "2.5"

esp8266:
  board: esp_wroom_02
  restore_from_flash: true

dashboard_import:
  package_import_url: github://Kaldek/esphome-ratgdo/rat-ratgdo-2MB.yaml@main

packages:
  remote_package:
    url: https://github.com/Kaldek/esphome-ratgdo
    files: [base.yaml]
    refresh: 1s

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

api:
  id: api_server

ota:

improv_serial:

wifi:
  ap:

logger:
